### ISSUE TITLE
[Bug] invalid isEqualObject where left side has undefined values

### ISSUE THREAD

**Issue by avrahamcool** [tjmoses/crud-compare#3]
https://github.com/tjmoses/crud-compare/blob/e3a44f64f6c7d57b57464446cae4aa87e30fcaed/src/index.ts#L10

```javascript
    const leftSide = {a: undefined};
    const rightSide = {b: "something"};

    console.log("are they equal??", leftSide, rightSide, isEqualObject(leftSide, rightSide));
```

![image](https://user-images.githubusercontent.com/5445320/102403095-6f7a8980-3fee-11eb-9ac7-f27f1bff0f4b.png)

they have the same amount of "keys", and each value that is present in "leftSide" is strictly equal to a value in the "rightSide".
but still - they are obviously not equal.

**Comment by tjmoses** [comment]
Originally I wasn't exposing the isEqualObject function and you can see in the other functions null/undefined checks are done before isEqualObject is ran. This is b/c the purpose of the library was to get the created, updated, and deleted values of an array of objects or an array of primitives alone for state comparison vs just comparing plain objects.

Anyways, good catch. I'll update this since I do want things to be 100% correct! Let me know if you see anything else.
