### ISSUE TITLE
[improvement] better key finding

### ISSUE THREAD

**Issue by avrahamcool** [tjmoses/crud-compare#9]
you mentioned in an other issue, that you are opting for performance.

there is a big improvement you can do - 
instead of declaring `originalItemKeys` and `activeItemKeys` as an array of keys, you can declare them as a regular objects (or es6 `Set`) - then, you don't need to use `indexOf` for checking if a key is already present. you decrease `O(n)` to `O(1)` for those checks.

https://github.com/tjmoses/crud-compare/blob/9792a747eae20ec4f8662181a271ff476d1a25d6/src/index.ts#L64
https://github.com/tjmoses/crud-compare/blob/9792a747eae20ec4f8662181a271ff476d1a25d6/src/index.ts#L71

```javascript

var originalItemKeys: any = {};
var activeItemKeys: any = {};

for (var i = 0; i < originalItem.length; i++) {
    var outerKeyVal = originalItem[i][key];
    originalItemKeys[outerKeyVal] = true;

    for (var j = 0; j < activeItem.length; j++) {
      if (i === 0) {
        activeItemKeys[activeItem[j][key]] = true;
      }

      if (i === originalItem.length - 1 && !originalItemKeys[activeItem[j][key]]) {
        createdVals.push(activeItem[j]);
      } else if (originalItem[i][key] === activeItem[j][key] && !isEqualObject(originalItem[i], activeItem[j])) {
        updatedVals.push(activeItem[j]);
      }
    }

    if (!activeItemKeys[outerKeyVal]) {
      deletedVals.push(originalItem[i]);
    }
  }
```

also: you referring a lot to `originalItem[i]` and `[activeItem[j]` - you should save them in a local variable.

**Comment by tjmoses** [comment]
On my prior comment about performance, I was speaking to not adding in additional function calls from your PR due to performance issues it would incur. Yes, performance in general is nice but people can go overboard with it as well.

Good call though, and I agree that using an Object, Map, or even Array with basic given keys would be faster. Although, if there were more complex common key values that were say other Objects/Arrays, there might be trouble iterating on the logic later. In addition, I would assume the browser hashes everything in memory for very quick look-ups with arrays even w/o good sorting. Also, you could get away with just creating a single object for the key value truthy check along with a boolean for the deleted val check. There are several ways of doing this.

Yes, local variables help as well for additional calls. There are _several_ additional performance factors, another quick one I see would be converting to while loops. I may opt for using the google closure compiler to automate most minute performance fixes in the future.

I will take your thoughts into consideration for the next release which will probably have updates for deep object checks as well.

Thanks!
